name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for deployment'
        required: true
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  
        
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Deploy application
        run: python deploy.py
