name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment for deployment'
        required: true
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - run: echo Deploying ${{ github.ref }} branch to ${{ inputs.environment }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}  

      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - run: pip install pyyaml requests boto3

      - name: Run deployment script
